//
//  WNDWeatherLanguageDefine.h
//
//  Created by unchi on 2014/06/04.
//  Copyright (c) 2014年 unchi. All rights reserved.
//

#if defined __WND_WEATHER_LANG_ENUM__
#define DEFINE_LANG(name, value)          WNDWeatherLanguage##name,
#elif defined __WND_WEATHER_LANG_CASE__
#define DEFINE_LANG(name, value)          case WNDWeatherLanguage##name: return value;
#else
#define DEFINE_LANG(name, value)
#endif

DEFINE_LANG(Afrikaans, @"AF")
DEFINE_LANG(Albanian, @"AL")
DEFINE_LANG(Arabic, @"AR")
DEFINE_LANG(Armenian, @"HY")
DEFINE_LANG(Azerbaijani, @"AZ")
DEFINE_LANG(Basque, @"EU")
DEFINE_LANG(Belarusian, @"BY")
DEFINE_LANG(Bulgarian, @"BU")
DEFINE_LANG(BritishEnglish, @"LI")
DEFINE_LANG(Burmese, @"MY")
DEFINE_LANG(Catalan, @"CA")
DEFINE_LANG(ChineseSimplified, @"CN")
DEFINE_LANG(ChineseTraditional, @"TW")
DEFINE_LANG(Croatian, @"CR")
DEFINE_LANG(Czech, @"CZ")
DEFINE_LANG(Danish, @"DK")
DEFINE_LANG(Dhivehi, @"DV")
DEFINE_LANG(Dutch, @"NL")
DEFINE_LANG(English, @"EN")
DEFINE_LANG(Esperanto, @"EO")
DEFINE_LANG(Estonian, @"ET")
DEFINE_LANG(Farsi, @"FA")
DEFINE_LANG(Finnish, @"FI")
DEFINE_LANG(French, @"FR")
DEFINE_LANG(FrenchCanadian, @"FC")
DEFINE_LANG(Galician, @"GZ")
DEFINE_LANG(German, @"DL")
DEFINE_LANG(Georgian, @"KA")
DEFINE_LANG(Greek, @"GR")
DEFINE_LANG(Gujarati, @"GU")
DEFINE_LANG(HaitianCreole, @"HT")
DEFINE_LANG(Hebrew, @"IL")
DEFINE_LANG(Hindi, @"HI")
DEFINE_LANG(Hungarian, @"HU")
DEFINE_LANG(Icelandic, @"IS")
DEFINE_LANG(Ido, @"IO")
DEFINE_LANG(Indonesian, @"ID")
DEFINE_LANG(IrishGaelic, @"IR")
DEFINE_LANG(Italian, @"IT")
DEFINE_LANG(Japanese, @"JP")
DEFINE_LANG(Javanese, @"JW")
DEFINE_LANG(Khmer, @"KM")
DEFINE_LANG(Korean, @"KR")
DEFINE_LANG(Kurdish, @"KU")
DEFINE_LANG(Latin, @"LA")
DEFINE_LANG(Latvian, @"LV")
DEFINE_LANG(Lithuanian, @"LT")
DEFINE_LANG(LowGerman, @"ND")
DEFINE_LANG(Macedonian, @"MK")
DEFINE_LANG(Maltese, @"MT")
DEFINE_LANG(Mandinka, @"GM")
DEFINE_LANG(Maori, @"MI")
DEFINE_LANG(Marathi, @"MR")
DEFINE_LANG(Mongolian, @"MN")
DEFINE_LANG(Norwegian, @"NO")
DEFINE_LANG(Occitan, @"OC")
DEFINE_LANG(Pashto, @"PS")
DEFINE_LANG(Plautdietsch, @"GN")
DEFINE_LANG(Polish, @"PL")
DEFINE_LANG(Portuguese, @"BR")
DEFINE_LANG(Punjabi, @"PA")
DEFINE_LANG(Romanian, @"RO")
DEFINE_LANG(Russian, @"RU")
DEFINE_LANG(Serbian, @"SR")
DEFINE_LANG(Slovak, @"SK")
DEFINE_LANG(Slovenian, @"SL")
DEFINE_LANG(Spanish, @"SP")
DEFINE_LANG(Swahili, @"SI")
DEFINE_LANG(Swedish, @"SW")
DEFINE_LANG(Swiss, @"CH")
DEFINE_LANG(Tagalog, @"TL")
DEFINE_LANG(Tatarish, @"TT")
DEFINE_LANG(Thai, @"TH")
DEFINE_LANG(Turkish, @"TR")
DEFINE_LANG(Turkmen, @"TK")
DEFINE_LANG(Ukrainian, @"UA")
DEFINE_LANG(Uzbek, @"UZ")
DEFINE_LANG(Vietnamese, @"VU")
DEFINE_LANG(Welsh, @"CY")
DEFINE_LANG(Wolof, @"SN")
DEFINE_LANG(YiddishTransliterated, @"JI")
DEFINE_LANG(YiddishUnicode, @"YI")

#undef DEFINE_LANG
